---
- name: nginx | Install passlib python library
  apt:
    name: python-passlib
    state: present

- name: nginx | Create htpasswd
  htpasswd:
    path: "/etc/nginx/htpasswd/{{ item.user }}---{{ item.password }}"
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    owner: root
    group: www-data
    mode: 0640
  with_items: "{{ nginx_htpasswd }}"
